// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AgendaDrawerController from "./agenda_drawer_controller"
application.register("agenda-drawer", AgendaDrawerController)

import AgendaHighlightController from "./agenda_highlight_controller"
application.register("agenda-highlight", AgendaHighlightController)

import AgendaItemController from "./agenda_item_controller"
application.register("agenda-item", AgendaItemController)

import AiChatDrawerController from "./ai_chat_drawer_controller"
application.register("ai-chat-drawer", AiChatDrawerController)

import AiUsageController from "./ai_usage_controller"
application.register("ai-usage", AiUsageController)

import AvatarCropController from "./avatar_crop_controller"
application.register("avatar-crop", AvatarCropController)

import CalendarViewController from "./calendar_view_controller"
application.register("calendar-view", CalendarViewController)

import ChatController from "./chat_controller"
application.register("chat", ChatController)

import ChatDrawerController from "./chat_drawer_controller"
application.register("chat-drawer", ChatDrawerController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import CountdownController from "./countdown_controller"
application.register("countdown", CountdownController)

import CourseFilterController from "./course_filter_controller"
application.register("course-filter", CourseFilterController)

import CurrentTimeController from "./current_time_controller"
application.register("current-time", CurrentTimeController)

import DeleteOptionsController from "./delete_options_controller"
application.register("delete-options", DeleteOptionsController)

import DraftCacheController from "./draft_cache_controller"
application.register("draft-cache", DraftCacheController)

import DraftDropdownController from "./draft_dropdown_controller"
application.register("draft-dropdown", DraftDropdownController)

import DrawerController from "./drawer_controller"
application.register("drawer", DrawerController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import DurationFillController from "./duration_fill_controller"
application.register("duration-fill", DurationFillController)

import EventPopoverController from "./event_popover_controller"
application.register("event-popover", EventPopoverController)

import FilepondController from "./filepond_controller"
application.register("filepond", FilepondController)

import FullHeightController from "./full_height_controller"
application.register("full-height", FullHeightController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NotificationsDropdownController from "./notifications_dropdown_controller"
application.register("notifications-dropdown", NotificationsDropdownController)

import PdfPreviewController from "./pdf_preview_controller"
application.register("pdf-preview", PdfPreviewController)

import PollFrameController from "./poll_frame_controller"
application.register("poll-frame", PollFrameController)

import ProfileNavController from "./profile_nav_controller"
application.register("profile-nav", ProfileNavController)

import RecurrenceToggleController from "./recurrence_toggle_controller"
application.register("recurrence-toggle", RecurrenceToggleController)

import RemovableCardController from "./removable_card_controller"
application.register("removable-card", RemovableCardController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import TypewriterController from "./typewriter_controller"
application.register("typewriter", TypewriterController)

import UsernameEditController from "./username_edit_controller"
application.register("username-edit", UsernameEditController)
